"""
Shared Pydantic models used across the entire application.
These define the data contracts between agents, tools, and the API.
"""

from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum


# ============================================================
# Enums
# ============================================================

class ScanStatus(str, Enum):
    """Possible states of a scan."""
    PENDING = "pending"
    PLANNING = "planning"
    EXECUTING = "executing"
    ANALYZING = "analyzing"
    REPORTING = "reporting"
    COMPLETED = "completed"
    FAILED = "failed"


class ReconStage(str, Enum):
    """Reconnaissance stages that the planner can choose from."""
    SUBDOMAIN_ENUMERATION = "subdomain_enumeration"
    DNS_ENUMERATION = "dns_enumeration"
    LIVE_HOSTS = "live_hosts"
    WEB_CRAWLING = "web_crawling"
    DIRECTORY_ENUMERATION = "directory_enumeration"
    TECHNOLOGY_DETECTION = "technology_detection"
    VULNERABILITY_SCAN = "vulnerability_scan"
    HISTORICAL_URLS = "historical_urls"
    JS_ANALYSIS = "js_analysis"
    CLOUD_ENUMERATION = "cloud_enumeration"


# ============================================================
# Planner Models
# ============================================================

class PlannedStage(BaseModel):
    """A single stage in the recon plan."""
    stage: ReconStage
    tools: list[str] = Field(description="Tool names to execute in this stage")
    description: str = Field(default="", description="Why this stage is needed")


class ReconPlan(BaseModel):
    """The full plan produced by the Planner Agent."""
    target: str = Field(description="Target domain or IP")
    objective: str = Field(description="What the user wants to achieve")
    plan: list[PlannedStage] = Field(description="Ordered list of recon stages")
    reasoning: str = Field(default="", description="Planner's reasoning for this plan")


# ============================================================
# Tool Output Models
# ============================================================

class ToolResult(BaseModel):
    """Normalized output from any recon tool."""
    tool: str = Field(description="Name of the tool that produced this output")
    category: str = Field(description="Category: subdomain, dns, live_host, url, vuln, etc.")
    target: str = Field(description="What target was scanned")
    results: list[str] = Field(default_factory=list, description="List of findings")
    raw_output: str = Field(default="", description="Raw stdout from the tool")
    error: str | None = Field(default=None, description="Error message if tool failed")
    execution_time: float = Field(default=0.0, description="Time taken in seconds")


# ============================================================
# Analysis Models
# ============================================================

class AnalyzedFinding(BaseModel):
    """A single finding from the Analysis Agent."""
    title: str
    severity: str = Field(description="critical, high, medium, low, info")
    description: str
    affected_assets: list[str] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)
    related_cves: list[str] = Field(default_factory=list)


class AnalysisResult(BaseModel):
    """Full analysis output."""
    summary: str
    total_assets_found: int = 0
    unique_subdomains: list[str] = Field(default_factory=list)
    live_hosts: list[str] = Field(default_factory=list)
    technologies: list[str] = Field(default_factory=list)
    findings: list[AnalyzedFinding] = Field(default_factory=list)
    next_steps: list[str] = Field(default_factory=list)


# ============================================================
# Report Models
# ============================================================

class ReconReport(BaseModel):
    """Final report generated by the Report Agent."""
    executive_summary: str
    technical_summary: str
    target: str
    scan_date: str = Field(default_factory=lambda: datetime.now().isoformat())
    assets_discovered: list[str] = Field(default_factory=list)
    interesting_hosts: list[str] = Field(default_factory=list)
    technologies: list[str] = Field(default_factory=list)
    vulnerabilities: list[AnalyzedFinding] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)
    full_markdown: str = Field(default="", description="Full report in Markdown format")


# ============================================================
# API Request/Response Models
# ============================================================

class ScanRequest(BaseModel):
    """User's request to start a new scan."""
    target: str = Field(description="Target domain, e.g. example.com")
    objective: str = Field(
        default="Perform a complete attack surface assessment",
        description="What the user wants to achieve"
    )


class ScanResponse(BaseModel):
    """Response after starting a scan."""
    scan_id: str
    status: ScanStatus
    message: str


class ChatMessage(BaseModel):
    """A single chat message."""
    role: str = Field(description="user or assistant")
    content: str
    scan_id: str | None = Field(default=None, description="Associated scan for context")


class ChatRequest(BaseModel):
    """Chat request from the frontend."""
    message: str
    scan_id: str | None = None


class ProgressUpdate(BaseModel):
    """Real-time progress update sent via WebSocket."""
    scan_id: str
    status: ScanStatus
    stage: str = ""
    tool: str = ""
    message: str = ""
    progress_percent: int = 0
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
